### ISSUE TITLE
Thank you for this amazing library

### ISSUE THREAD

**Issue by iongion** [parallel-execute/parallel-execute#12]
Not an issue at all, but just wanted to bring it up, thanks for this super useful tool!
It helps so much having clean design!

**Comment by sahilrp** [comment]
Thanks for appreciating it, stay tuned for upcoming release. more features are on the way :)

**Comment by sahilrp** [comment]
@iongion - Please checkout the rebranded version with more features: 
https://github.com/Concurra/concurra
https://pypi.org/project/concurra/
